name: CI

on: [push,pull_request]

jobs:
  build:
    
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    #- uses: actions/checkout@v1
    #- name: Build
    #  run:  xcodebuild -project UnitSample.xcodeproj -scheme "UnitSample"  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro'  -configuration Debug  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
    - name: Run tests
      id:  xcodetest
      run: 
        xcodebuild -project UnitSample.xcodeproj -scheme "UnitSample" -testPlan "UnitSample1"  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro'  -configuration Debug  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -resultBundlePath "testReports/TestResult.xcresult" test > mycustomfile
        if grep -q "** TEST FAILED **" mycustomfile
        then
        echo "Test has failed so exiting..."
        exit 1
        else
        cat mycustomfile | xcpretty --test --color --report html --output TestReports/report.html
        fi
        rm mycustomfile
        echo "::set-output name=estatus::$PIPESTATUS"
    - name: Test Reports
      uses: actions/upload-artifact@v1
      with:
          name: testReports
          path: TestReports
    - name: Check Tests Passed
      if: steps.xcodetest.outputs.estatus != 0
      run: exit 1
