name: CI

on: [push,pull_request]

jobs:
  build:
    
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run:  xcrun xcodebuild -project UnitSample.xcodeproj -scheme "UnitSample"  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro'  -configuration Debug  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
    - name: Run tests
      run: xcrun xcodebuild -project UnitSample.xcodeproj -scheme "UnitSample"  -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro'  -configuration Debug  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -resultBundlePath "testReports/TestResult.xcresult" test | xcpretty --color --report html --output TestReports/report.html  
    - name: Test Reports
      if: failure()
      uses: actions/upload-artifact@v1
      with:
          name: testReports
          path: testReports
